#!/usr/bin/env python3
"""Build the local Czatbox TT gift catalog from tapujemy.pl/gifts."""

from __future__ import annotations

import argparse
import html
import io
import json
import re
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from PIL import Image


SOURCE_URL = "https://tapujemy.pl/gifts"
CARD_PATTERN = re.compile(
    r'<div class="[^"]*gift-item[^"]*"[^>]*'
    r'data-price="(?P<price>\d+)"[^>]*'
    r'data-name="(?P<data_name>[^"]*)"[^>]*'
    r'data-id="(?P<id>\d+)"[^>]*>.*?'
    r'<img\s+src="(?P<image>[^"]+)"\s+alt="(?P<name>[^"]*)"',
    re.IGNORECASE | re.DOTALL,
)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "Czatbox-TT gift catalog updater/1.0"},
    )
    with urllib.request.urlopen(request, timeout=45) as response:
        return response.read()


def parse_catalog(source: str) -> list[dict[str, object]]:
    records: dict[str, dict[str, object]] = {}
    for match in CARD_PATTERN.finditer(source):
        gift_id = match.group("id")
        if gift_id in records:
            raise ValueError(f"Duplicate gift ID: {gift_id}")
        records[gift_id] = {
            "id": gift_id,
            "name": html.unescape(match.group("name")).strip() or f"Gift {gift_id}",
            "coins": int(match.group("price")),
            "sourceImage": html.unescape(match.group("image")).strip(),
        }
    if len(records) < 100:
        raise ValueError(f"Catalog looks incomplete: only {len(records)} records")
    return sorted(records.values(), key=lambda item: (int(item["coins"]), int(item["id"])))


def convert_image(record: dict[str, object], target_dir: Path) -> tuple[str, bool, str]:
    gift_id = str(record["id"])
    target = target_dir / f"{gift_id}.webp"
    if target.exists() and target.stat().st_size > 0:
        return gift_id, True, ""
    last_error = ""
    for attempt in range(3):
        try:
            payload = fetch(str(record["sourceImage"]))
            with Image.open(io.BytesIO(payload)) as source:
                image = source.convert("RGBA")
                image.thumbnail((128, 128), Image.Resampling.LANCZOS)
                canvas = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
                canvas.alpha_composite(image, ((128 - image.width) // 2, (128 - image.height) // 2))
                canvas.save(target, "WEBP", lossless=True, method=6)
            return gift_id, True, ""
        except Exception as error:  # noqa: BLE001 - report every failed external asset
            last_error = str(error)
            time.sleep(attempt + 1)
    return gift_id, False, last_error


def write_catalog(records: list[dict[str, object]], output: Path) -> None:
    entries = {
        str(record["id"]): {
            "name": record["name"],
            "coins": record["coins"],
            "image": f"/gifts/{record['id']}.webp",
        }
        for record in records
    }
    payload = json.dumps(entries, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    output.write_text(
        "// Generated by tools/sync-tiktok-gifts.py from https://tapujemy.pl/gifts\n"
        f"window.CZATBOX_GIFT_CATALOG=Object.freeze({payload});\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--workers", type=int, default=10)
    args = parser.parse_args()

    public_dir = args.root / "web-client" / "public"
    image_dir = public_dir / "gifts"
    image_dir.mkdir(parents=True, exist_ok=True)

    source = fetch(SOURCE_URL).decode("utf-8", errors="replace")
    records = parse_catalog(source)
    expected = {f"{record['id']}.webp" for record in records}
    failures: list[tuple[str, str]] = []

    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as executor:
        jobs = [executor.submit(convert_image, record, image_dir) for record in records]
        for index, future in enumerate(as_completed(jobs), start=1):
            gift_id, ok, error = future.result()
            if not ok:
                failures.append((gift_id, error))
            if index % 100 == 0 or index == len(jobs):
                print(f"images: {index}/{len(jobs)}", file=sys.stderr)

    if failures:
        for gift_id, error in failures:
            print(f"FAILED {gift_id}: {error}", file=sys.stderr)
        return 1

    for stale in image_dir.glob("*.webp"):
        if stale.name not in expected:
            stale.unlink()

    write_catalog(records, public_dir / "gift-catalog.js")
    manifest = {
        "source": SOURCE_URL,
        "records": len(records),
        "images": len(expected),
        "minCoins": min(int(record["coins"]) for record in records),
        "maxCoins": max(int(record["coins"]) for record in records),
    }
    (image_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(manifest, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
